#! /bin/bash
# pandoc-highlight-style-demo
# Pandoc's existing highlight styles given by
# pandoc --list-highlight-styles
# are:
# pygments
# tango
# espresso
# zenburn
# kate
# monochrome
# breezedark
# haddock
# 
# This script produces HTML5 fragment output for the same code fragment 
# from each highlighting style so that they may be combined into
# a single HTML5 file for easy comparison.
# 
# R (Chandra) Chandrasekhar
# independent Scholar, Thinker, Author, Researcher (iSTAR)
# lnesqrt1cos0@gmail.com | chyavana@gmail.com
# First written: 2020-04-23
# Last revised : 2020-04-23

# Change directory to /tmp so that cleanup is not required

mkdir -p /tmp/highlighting
cd /tmp/highlighting

declare -a highlighting_style=(pygments tango espresso zenburn kate monochrome breezedark haddock)

echo "Whole Hog" > "whole-hog.html"

for hs in "${highlighting_style[@]}"
do
cat <<- EOF > "code.md"
---
title: "Highlighting Style Comparison"
---

"$hs"

~~~bash
#! /bin/bash
echo "Hello World"
~~~
EOF

pandoc --from markdown --to html5 --standalone --highlight-style="$hs" --output "$hs.html" "code.md"

cat "$hs.html" >> "whole-hog.html"
done
