#! /bin/bash
# Special make file ofr generating PDF onl;y for this blog
#
base="asking-questions-in-english"
#
sed -e 's|{attach}||g' "$base.md" | sed -e 's|\\boldsymbol|\\symbf|g' > "temp.md"
#
blogheader="$HOME/.pandoc/defaults/blog-header-includes.tex"
# defaults files to use
standard="$HOME/.pandoc/defaults/latex.yaml"
stdheader="$HOME/.pandoc/defaults/latex-header-includes.tex"
merriweather="$HOME/.pandoc/defaults/fonts/merriweather-plus.tex"
indicgreek="$HOME/.pandoc/defaults/fonts/indic-greek-fonts.tex"

pandoc --defaults "$standard" --include-in-header "$stdheader" --include-in-header "$merriweather" --include-in-header "$indicgreek" --include-in-header "$blogheader" --include-in-header "./special-includes" --output "$base.pdf" "temp.md";
#
pandoc --defaults "$standard"  --include-in-header "$stdheader" --include-in-header "$merriweather" --include-in-header "$indicgreek" --include-in-header "$blogheader" --include-in-header "./special-includes" --output "$base.tex" "temp.md";


# pandoc --defaults xelatex.yaml --include-in-header "$blogheader" --include-in-header "./special-includes" --output "$base.pdf" "temp.md";
# #
#     pandoc --defaults xelatex.yaml --include-in-header "$blogheader" --output "$base.tex" "temp.md";

/usr/bin/rm "temp.md"
