#!/bin/bash
# make-html-pdf
# Generate HTML and PDF output from Markdown source featuring
# Font Awesome icons.
#

pandoc --from markdown --to html5 --defaults html-defaults.yaml --include-in-header html-header-includes --css awesome.css --standalone --output opening-html opening-html.txt

pandoc --from markdown --to latex --pdf-engine lualatex --defaults latex-defaults.yaml --defaults latex-font.yaml --include-in-header latex-header-includes.tex --include-before-body latex-before-body-includes.tex --standalone --output opening-latex.pdf opening-latex.txt
